import type { SimEvent } from "@/lib/simulation-store";

export type SimulatorScenario = {
  id: string;
  title: string;
  focus: string;
  baseState: Record<string, string>;
  events: SimEvent[];
  nodes: { id: string; label: string; x: number; y: number }[];
  flowEdges: { source: string; target: string; activateAtStep: number }[];
  whyThisExists: string;
  deterministicBoundary: string;
};

export const simulatorScenarios: Record<string, SimulatorScenario> = {
  "tx-flow": {
    id: "tx-flow",
    title: "Transaction Flow Simulator",
    focus: "From packet ingress to committed state.",
    whyThisExists: "Explains how validators transform signed intent into deterministic state updates.",
    deterministicBoundary: "Determinism begins after ordered packets and verified signatures.",
    baseState: {
      signatureStatus: "unverified",
      accountLocks: "none",
      executionResult: "pending",
      commitSlot: "uncommitted",
    },
    events: [
      { stage: "Ingress", detail: "Leader receives transaction packet.", statePatch: { signatureStatus: "queued" } },
      { stage: "Signature Verify", detail: "Validator verifies signer authenticity.", statePatch: { signatureStatus: "verified" } },
      { stage: "Lock Planning", detail: "Runtime computes account read/write locks.", statePatch: { accountLocks: "planned" } },
      { stage: "Parallel Scheduler", detail: "Non-conflicting tx assigned to execution lanes.", statePatch: { accountLocks: "acquired" } },
      { stage: "Instruction Execution", detail: "Program logic and CPI checks run deterministically.", statePatch: { executionResult: "success" } },
      { stage: "Commit", detail: "State delta committed to next bank slot.", statePatch: { commitSlot: "committed@slotN" } },
    ],
    nodes: [
      { id: "user", label: "User", x: 0, y: 60 },
      { id: "leader", label: "Leader", x: 220, y: 60 },
      { id: "runtime", label: "Runtime", x: 450, y: 60 },
      { id: "validator", label: "Validator", x: 680, y: 60 },
    ],
    flowEdges: [
      { source: "user", target: "leader", activateAtStep: 1 },
      { source: "leader", target: "runtime", activateAtStep: 3 },
      { source: "runtime", target: "validator", activateAtStep: 5 },
    ],
  },
  "account-ownership": {
    id: "account-ownership",
    title: "Account Ownership Simulator",
    focus: "Mutation rights are enforced by owner program and signer authority.",
    whyThisExists: "Parallel runtimes need explicit write authority boundaries to prevent arbitrary state mutation.",
    deterministicBoundary: "Given owner program, signer set, and instruction, write permission checks are deterministic.",
    baseState: {
      ownerProgram: "ProgramA",
      signerAuth: "unchecked",
      writePermission: "unknown",
      mutationStatus: "pending",
    },
    events: [
      { stage: "Account Load", detail: "Runtime loads account metadata including owner field.", statePatch: { ownerProgram: "ProgramA" } },
      { stage: "Signer Check", detail: "Runtime verifies required signer is present.", statePatch: { signerAuth: "valid-signer-present" } },
      { stage: "Owner Match", detail: "Instruction program id is matched against account owner.", statePatch: { writePermission: "owner-matched" } },
      { stage: "Unauthorized Branch", detail: "Attempt from ProgramB is rejected deterministically.", statePatch: { writePermission: "ProgramB-denied" } },
      { stage: "Authorized Mutation", detail: "ProgramA write path is accepted.", statePatch: { mutationStatus: "write-applied" } },
      { stage: "Commit", detail: "Updated account data is committed.", statePatch: { mutationStatus: "committed" } },
    ],
    nodes: [
      { id: "user", label: "User", x: 0, y: 60 },
      { id: "prog-a", label: "Program A", x: 210, y: 20 },
      { id: "prog-b", label: "Program B", x: 210, y: 110 },
      { id: "runtime", label: "Runtime", x: 430, y: 60 },
      { id: "account", label: "Owned Account", x: 660, y: 60 },
    ],
    flowEdges: [
      { source: "user", target: "prog-a", activateAtStep: 1 },
      { source: "user", target: "prog-b", activateAtStep: 3 },
      { source: "prog-a", target: "runtime", activateAtStep: 2 },
      { source: "prog-b", target: "runtime", activateAtStep: 4 },
      { source: "runtime", target: "account", activateAtStep: 5 },
    ],
  },
  "memory-state": {
    id: "memory-state",
    title: "Memory And State Mutation Simulator",
    focus: "Differentiate transient execution memory from committed account state.",
    whyThisExists: "Protocol engineers must separate speculative execution deltas from canonical committed state.",
    deterministicBoundary: "Only validated deltas are committed; failed paths are discarded identically across validators.",
    baseState: {
      memoryFrame: "empty",
      pendingDelta: "none",
      commitStatus: "not-committed",
      stateRootHint: "S0",
    },
    events: [
      { stage: "Frame Init", detail: "Runtime allocates instruction execution frame.", statePatch: { memoryFrame: "frame-open" } },
      { stage: "Read Snapshot", detail: "Account data snapshot is loaded into VM memory.", statePatch: { pendingDelta: "snapshot-loaded" } },
      { stage: "Apply Delta", detail: "Instruction computes in-memory state delta.", statePatch: { pendingDelta: "delta:+balance,-liquidity" } },
      { stage: "Invariant Check", detail: "Runtime validates constraints before commit.", statePatch: { commitStatus: "checks-passed" } },
      { stage: "Commit Delta", detail: "Delta is written to canonical account store.", statePatch: { commitStatus: "committed", stateRootHint: "S1" } },
      { stage: "Frame Close", detail: "Transient memory is discarded after commit.", statePatch: { memoryFrame: "closed" } },
    ],
    nodes: [
      { id: "vm", label: "Instruction VM", x: 0, y: 60 },
      { id: "runtime", label: "Runtime", x: 230, y: 60 },
      { id: "mem", label: "Memory Frame", x: 460, y: 20 },
      { id: "store", label: "Account Store", x: 460, y: 120 },
      { id: "state", label: "Canonical State", x: 690, y: 60 },
    ],
    flowEdges: [
      { source: "vm", target: "runtime", activateAtStep: 1 },
      { source: "runtime", target: "mem", activateAtStep: 2 },
      { source: "mem", target: "runtime", activateAtStep: 4 },
      { source: "runtime", target: "store", activateAtStep: 5 },
      { source: "store", target: "state", activateAtStep: 5 },
    ],
  },
  "block-production": {
    id: "block-production",
    title: "Block Production Simulator",
    focus: "Leader scheduling, packet batching, PoH entry generation, and block finalize.",
    whyThisExists: "High-throughput chains require deterministic block assembly under rotating leadership.",
    deterministicBoundary: "Within a selected leader slot, entry ordering and included transactions must replay identically.",
    baseState: {
      leaderSlot: "unassigned",
      packetBatch: "empty",
      entryStream: "idle",
      blockStatus: "building",
    },
    events: [
      { stage: "Leader Schedule", detail: "Current validator becomes slot leader.", statePatch: { leaderSlot: "slot-842991" } },
      { stage: "Packet Intake", detail: "Leader receives transaction packets from network.", statePatch: { packetBatch: "received:512" } },
      { stage: "Batch Verify", detail: "Signatures and basic validity are filtered.", statePatch: { packetBatch: "verified:467" } },
      { stage: "PoH Entries", detail: "Leader appends ordered entries to PoH stream.", statePatch: { entryStream: "entries:96" } },
      { stage: "Block Assemble", detail: "Entries are grouped into a produced block candidate.", statePatch: { blockStatus: "candidate-ready" } },
      { stage: "Broadcast", detail: "Block is broadcast for replay and vote.", statePatch: { blockStatus: "broadcast" } },
    ],
    nodes: [
      { id: "sched", label: "Leader Schedule", x: 0, y: 60 },
      { id: "leader", label: "Leader", x: 220, y: 60 },
      { id: "poh", label: "PoH Stream", x: 440, y: 20 },
      { id: "bank", label: "Banking Stage", x: 440, y: 110 },
      { id: "block", label: "Block Store", x: 680, y: 60 },
    ],
    flowEdges: [
      { source: "sched", target: "leader", activateAtStep: 1 },
      { source: "leader", target: "bank", activateAtStep: 2 },
      { source: "leader", target: "poh", activateAtStep: 4 },
      { source: "poh", target: "block", activateAtStep: 5 },
      { source: "bank", target: "block", activateAtStep: 5 },
    ],
  },
  "parallel-execution": {
    id: "parallel-execution",
    title: "Parallel Execution Deep Simulator",
    focus: "Lock table and lane scheduler behavior under read/write conflicts.",
    whyThisExists: "Throughput gains come from safe concurrency, not optimistic nondeterminism.",
    deterministicBoundary: "Given declared account metas, lane assignment and conflict resolution are deterministic.",
    baseState: {
      laneMap: "empty",
      rwConflicts: "none",
      lockTable: "clear",
      completionOrder: "pending",
    },
    events: [
      { stage: "Tx Set Intake", detail: "Scheduler receives transactions with declared read/write sets.", statePatch: { laneMap: "tx1,tx2,tx3,tx4" } },
      { stage: "Conflict Scan", detail: "Runtime computes write-write and read-write overlaps.", statePatch: { rwConflicts: "tx2<->tx3 on accountY" } },
      { stage: "Lock Allocation", detail: "Non-conflicting transactions acquire account locks.", statePatch: { lockTable: "laneA:tx1 laneB:tx4 laneC:tx2" } },
      { stage: "Deferred Queue", detail: "Conflicting tx3 is deferred to next execution wave.", statePatch: { laneMap: "wave1:tx1,tx2,tx4 | wave2:tx3" } },
      { stage: "Wave Commit", detail: "Wave1 commits, locks released deterministically.", statePatch: { lockTable: "released-wave1" } },
      { stage: "Final Commit", detail: "Deferred tx3 executes and completion order is finalized.", statePatch: { completionOrder: "tx1>tx2>tx4>tx3" } },
    ],
    nodes: [
      { id: "in", label: "Scheduler Intake", x: 0, y: 60 },
      { id: "scan", label: "Conflict Scan", x: 200, y: 60 },
      { id: "locks", label: "Lock Manager", x: 400, y: 20 },
      { id: "lanes", label: "Execution Lanes", x: 400, y: 110 },
      { id: "commit", label: "Runtime Commit", x: 650, y: 60 },
    ],
    flowEdges: [
      { source: "in", target: "scan", activateAtStep: 1 },
      { source: "scan", target: "locks", activateAtStep: 2 },
      { source: "locks", target: "lanes", activateAtStep: 3 },
      { source: "lanes", target: "commit", activateAtStep: 5 },
    ],
  },
  "validator-internals": {
    id: "validator-internals",
    title: "Validator Internals Deep Simulator",
    focus: "Deep dive into fetch, sigverify, banking, replay, and vote stages.",
    whyThisExists: "Protocol reliability depends on understanding validator runtime internals, not just contract APIs.",
    deterministicBoundary: "Stage outputs must compose identically across all validators for safe voting.",
    baseState: {
      packetQueue: "0",
      verifiedQueue: "0",
      bankFork: "unknown",
      voteState: "idle",
    },
    events: [
      { stage: "Fetch Stage", detail: "Packets are fetched from turbine/gossip paths.", statePatch: { packetQueue: "620" } },
      { stage: "SigVerify Stage", detail: "GPU/CPU signature verification filters invalid packets.", statePatch: { verifiedQueue: "571" } },
      { stage: "Banking Stage", detail: "Verified packets execute against working bank fork.", statePatch: { bankFork: "forkA@slotN" } },
      { stage: "Replay Stage", detail: "Fork replay computes bank hash and validity.", statePatch: { bankFork: "forkA:hash-ok" } },
      { stage: "Fork Choice", detail: "Validator compares local fork weights.", statePatch: { voteState: "candidate:forkA" } },
      { stage: "Vote Emit", detail: "Validator emits vote transaction for chosen fork.", statePatch: { voteState: "voted:forkA" } },
    ],
    nodes: [
      { id: "fetch", label: "Fetch", x: 0, y: 60 },
      { id: "sig", label: "SigVerify", x: 170, y: 60 },
      { id: "bank", label: "Banking", x: 340, y: 60 },
      { id: "replay", label: "Replay", x: 510, y: 60 },
      { id: "vote", label: "Vote", x: 680, y: 60 },
    ],
    flowEdges: [
      { source: "fetch", target: "sig", activateAtStep: 1 },
      { source: "sig", target: "bank", activateAtStep: 2 },
      { source: "bank", target: "replay", activateAtStep: 4 },
      { source: "replay", target: "vote", activateAtStep: 6 },
    ],
  },
  "pda-derivation": {
    id: "pda-derivation",
    title: "PDA Derivation Simulator",
    focus: "Deterministic address derivation and authority checks.",
    whyThisExists: "Programs need stable state locations without private keys.",
    deterministicBoundary: "Given identical seeds + program id, address derivation is deterministic.",
    baseState: {
      seeds: "unbound",
      bump: "unknown",
      derivedAddress: "not-derived",
      signerCheck: "not-evaluated",
    },
    events: [
      { stage: "Seed Definition", detail: "Protocol defines canonical seeds for state namespace.", statePatch: { seeds: "vault,user,mint" } },
      { stage: "Program ID Binding", detail: "Seeds are bound to program id domain.", statePatch: { derivedAddress: "candidate-derived" } },
      { stage: "Bump Search", detail: "Runtime finds valid bump for off-curve PDA.", statePatch: { bump: "254" } },
      { stage: "PDA Materialization", detail: "Derived address is finalized deterministically.", statePatch: { derivedAddress: "pda:9xQ...K2" } },
      { stage: "Signer Constraint Check", detail: "Runtime validates invoke_signed seed proof.", statePatch: { signerCheck: "passed" } },
      { stage: "State Write", detail: "Program writes protocol state through PDA authority.", statePatch: { signerCheck: "passed+write-authorized" } },
    ],
    nodes: [
      { id: "client", label: "Client", x: 0, y: 60 },
      { id: "program", label: "Program", x: 230, y: 60 },
      { id: "runtime", label: "Runtime", x: 460, y: 60 },
      { id: "pda", label: "PDA Account", x: 690, y: 60 },
    ],
    flowEdges: [
      { source: "client", target: "program", activateAtStep: 1 },
      { source: "program", target: "runtime", activateAtStep: 2 },
      { source: "runtime", target: "pda", activateAtStep: 4 },
    ],
  },
  "cpi-stack": {
    id: "cpi-stack",
    title: "CPI Call Stack Simulator",
    focus: "Nested program execution with bounded authority propagation.",
    whyThisExists: "Composable finance needs safe cross-program execution.",
    deterministicBoundary: "Deterministic call ordering and explicit account metas preserve replay equivalence.",
    baseState: {
      callDepth: "0",
      accountAccess: "root-program-only",
      authorityGraph: "root",
      invariants: "unchecked",
    },
    events: [
      { stage: "Entry Instruction", detail: "Program A receives instruction and accounts.", statePatch: { callDepth: "1", accountAccess: "A(read/write set)" } },
      { stage: "Pre-CPI Validation", detail: "Program A validates required invariants.", statePatch: { invariants: "A-precheck-passed" } },
      { stage: "Invoke Program B", detail: "Runtime pushes CPI frame with scoped accounts.", statePatch: { callDepth: "2", authorityGraph: "A->B" } },
      { stage: "Token Program CPI", detail: "Program B invokes token movement with delegated authority.", statePatch: { callDepth: "3", authorityGraph: "A->B->Token" } },
      { stage: "Unwind + Postcheck", detail: "Frames unwind; root program verifies end-state invariants.", statePatch: { callDepth: "1", invariants: "postcheck-passed" } },
      { stage: "Commit", detail: "Runtime commits composed state transition.", statePatch: { callDepth: "0", accountAccess: "committed", invariants: "safe" } },
    ],
    nodes: [
      { id: "prog-a", label: "Program A", x: 0, y: 60 },
      { id: "runtime", label: "Runtime", x: 230, y: 60 },
      { id: "prog-b", label: "Program B", x: 460, y: 60 },
      { id: "token", label: "Token Program", x: 690, y: 60 },
    ],
    flowEdges: [
      { source: "prog-a", target: "runtime", activateAtStep: 1 },
      { source: "runtime", target: "prog-b", activateAtStep: 3 },
      { source: "prog-b", target: "token", activateAtStep: 4 },
    ],
  },
  "fork-consensus": {
    id: "fork-consensus",
    title: "Fork And Consensus Simulator",
    focus: "Competing forks, replay, and vote convergence.",
    whyThisExists: "Distributed systems must converge even with temporary chain divergence.",
    deterministicBoundary: "Fork choice becomes deterministic under finalized vote lockouts.",
    baseState: {
      leaderSlot: "slotN",
      forkChoice: "unresolved",
      voteWeight: "split",
      finalizedHead: "none",
    },
    events: [
      { stage: "Block Proposal", detail: "Leader proposes block at slot N.", statePatch: { leaderSlot: "slotN", forkChoice: "A-candidate" } },
      { stage: "Competing Fork", detail: "Network delay reveals alternate block for same slot.", statePatch: { forkChoice: "A vs B" } },
      { stage: "Replay", detail: "Validators replay both candidates against local bank state.", statePatch: { voteWeight: "evaluating" } },
      { stage: "Voting", detail: "Validators vote fork with valid replay and higher cumulative weight.", statePatch: { voteWeight: "A:68 B:32", forkChoice: "A-leading" } },
      { stage: "Lockout", detail: "Vote lockouts increase commitment to chosen fork.", statePatch: { finalizedHead: "optimistic:A" } },
      { stage: "Finalization", detail: "Supermajority convergence finalizes canonical fork head.", statePatch: { forkChoice: "A-canonical", finalizedHead: "A-final" } },
    ],
    nodes: [
      { id: "leader", label: "Leader", x: 0, y: 60 },
      { id: "fork-a", label: "Fork A", x: 220, y: 10 },
      { id: "fork-b", label: "Fork B", x: 220, y: 110 },
      { id: "validators", label: "Validator Set", x: 470, y: 60 },
      { id: "finality", label: "Finality", x: 700, y: 60 },
    ],
    flowEdges: [
      { source: "leader", target: "fork-a", activateAtStep: 1 },
      { source: "leader", target: "fork-b", activateAtStep: 2 },
      { source: "fork-a", target: "validators", activateAtStep: 3 },
      { source: "fork-b", target: "validators", activateAtStep: 3 },
      { source: "validators", target: "finality", activateAtStep: 6 },
    ],
  },
};
